[package]
name = "cursive_tree_view"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
description = "A tree view implementation for cursive."
repository = "https://github.com/BonsaiDen/cursive_tree_view.git"
readme = "README.md"
keywords = ["cursive", "ncurses", "TUI", "UI", "tree"]
categories = ["command-line-interface", "gui"]
license = "MIT/Apache-2.0"

[dependencies]
cursive = "0.5"

[features]
default = ["ncurses-backend"]
ncurses-backend = ["cursive/ncurses-backend"]
pancurses-backend = ["cursive/pancurses-backend"]
termion-backend = ["cursive/termion-backend"]
blt-backend = ["cursive/blt-backend"]

